---
title: 异常
categories:
- 后端
tags: 异常
date: 2021-04-18
---

> 异常类Exception的父类是Throwable,其子类包括IOException及RuntimeException。

## 异常的类型
- 检查性异常：最具代表的检查性异常是用户错误或问题引起的异常，这是程序员无法预见的。例如要打开一个不存在文件时，一个异常就发生了，这些异常在编译时不能被简单地忽略。
- 运行时异常：运行时异常是可能被程序员避免的异常。与检查性异常相反，运行时异常可以在编译时被忽略。
- 错误：错误不是异常，而是脱离程序员控制的问题。错误在代码中通常被忽略。例如，当栈溢出时，一个错误就发生了，它们在编译也检查不到的。

## 异常的处理方式
- 捕获异常： try/catch或者try/catch/finally
- 抛出异常： throw/throws关键字(**注意两个关键字的区别及使用位置**)
  1. 在方法内部逻辑上通过关键字throw抛出异常；
  2. 在方法声明(也就是方法名后面)通过关键字throws对外声明异常；
  ~~~
    /**
    * 异常处理
    * throw/throws
    */
    public class ExceptionDemo02 {
        public static void main(String[] args) throws Exception {
            int a = 1;
            int b = 0;
            if (b == 0){
                throw new Exception();
            }

        }
    }
    ~~~

## throw的使用注意事项
1. 使用在方法体内；
2. throw抛出的异常对象必须是Exception的子类，即使是自己定于的异常类也是继承了Exception。
3. 方法体内使用了关键字throw，那么一定要用throws对外声明异常；相反一个方法的声明上使用了关键字throws，方法体内不一定需要使用throw；
~~~
/**
 * 异常
 * 只对外声明异常
 */
public class ExcepltionDemo03Throws {
    public static void main(String[] args) {
        try {
            testThrows();
        } catch (Exception e) {
            e.printStackTrace();
        }
        testThrow();
    }

    private static void testThrow() {
        int a = 1;
        int b = 0;
        if(b == 0){
            throw new Exception();  //此处编译报错
        }
    }

    private static void testThrows() throws Exception{
        String a = "a";
        int b = 1/0;
    }
}
~~~



